package za.belgiumcampus.cleaninginventory.view.dashboard;
import za.belgiumcampus.cleaninginventory.controller.DashboardController;
import za.belgiumcampus.cleaninginventory.model.User;

public class DashboardsForm extends javax.swing.JPanel {
    
    private final DashboardController controller = new DashboardController();
    
    private User currentUser;
    
    public DashboardsForm(User user) {
        initComponents();
        currentUser = user;
        lblWelcome.setText("Welcome back, " + currentUser.getUsername());
        loadDashboard();     
    }
    private void loadDashboard() {
        lblMaterialInt.setText(String.valueOf(controller.getTotalMaterials()));
        lblTotalCleanersInt.setText(String.valueOf(controller.getTotalCleaners()));
        lblLowStockInt.setText(String.valueOf(controller.getLowStockCount()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        pnlMaterials = new javax.swing.JPanel();
        lblMaterialInt = new javax.swing.JLabel();
        lblMaterialTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLowStockTitle = new javax.swing.JLabel();
        lblLowStockInt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTotalCleanersTitle = new javax.swing.JLabel();
        lblTotalCleanersInt = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTotalUsersTitle = new javax.swing.JLabel();
        lblTotalUsersInt = new javax.swing.JLabel();
        lblRecentAcivity = new javax.swing.JLabel();

        setName("DashboardForm"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Cleaner", "Material", "Qty"
            }
        ));
        jTable1.setName("tblRecentIssues"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jButton1.setLabel("Refresh");
        jButton1.setName("btnRefresh"); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Dashboard");

        lblWelcome.setText("Welcome back, Administrator!");

        lblMaterialInt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaterialInt.setText("Total Materials");
        lblMaterialInt.setName("lblMaterialInt"); // NOI18N

        lblMaterialTitle.setText("Materials Count:");

        javax.swing.GroupLayout pnlMaterialsLayout = new javax.swing.GroupLayout(pnlMaterials);
        pnlMaterials.setLayout(pnlMaterialsLayout);
        pnlMaterialsLayout.setHorizontalGroup(
            pnlMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaterialsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaterialTitle)
                    .addComponent(lblMaterialInt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMaterialsLayout.setVerticalGroup(
            pnlMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMaterialsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMaterialTitle)
                .addGap(39, 39, 39)
                .addComponent(lblMaterialInt)
                .addContainerGap())
        );

        lblLowStockTitle.setText("Low Stock:");
        lblLowStockTitle.setName("lblLowStockInt"); // NOI18N

        lblLowStockInt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLowStockInt.setText("Low Stock");
        lblLowStockInt.setName("lblLowStockInt"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLowStockTitle)
                    .addComponent(lblLowStockInt))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLowStockTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblLowStockInt)
                .addGap(28, 28, 28))
        );

        lblTotalCleanersTitle.setText("Total Cleaners:");
        lblTotalCleanersTitle.setName("lblTotalCleanersInt"); // NOI18N

        lblTotalCleanersInt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalCleanersInt.setText("Total Cleaners");
        lblTotalCleanersInt.setName("lblTotalCleanersInt"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalCleanersTitle)
                    .addComponent(lblTotalCleanersInt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalCleanersTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblTotalCleanersInt)
                .addGap(29, 29, 29))
        );

        lblTotalUsersTitle.setText("Total Users:");
        lblTotalUsersTitle.setName("lblTotalUsersInt"); // NOI18N

        lblTotalUsersInt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalUsersInt.setText("Total Users");
        lblTotalUsersInt.setName("lblTotalUsersInt"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalUsersTitle)
                    .addComponent(lblTotalUsersInt))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalUsersTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lblTotalUsersInt)
                .addGap(27, 27, 27))
        );

        lblRecentAcivity.setText("Recent Acitvity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRecentAcivity)
                                .addGap(30, 30, 30)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWelcome)
                            .addComponent(lblTitle))))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRecentAcivity)
                            .addComponent(jButton1)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblLowStockInt;
    private javax.swing.JLabel lblLowStockTitle;
    private javax.swing.JLabel lblMaterialInt;
    private javax.swing.JLabel lblMaterialTitle;
    private javax.swing.JLabel lblRecentAcivity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCleanersInt;
    private javax.swing.JLabel lblTotalCleanersTitle;
    private javax.swing.JLabel lblTotalUsersInt;
    private javax.swing.JLabel lblTotalUsersTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlMaterials;
    // End of variables declaration//GEN-END:variables

}
