package za.belgiumcampus.cleaninginventory.view.dashboard;
import za.belgiumcampus.cleaninginventory.controller.DashboardController;

public class DashboardsForm extends javax.swing.JPanel {
    
    private final DashboardController controller = new DashboardController();
    /**
     * Creates new form DashboardsForm
     */
    public DashboardsForm() {
        initComponents();
        loadDashboard();     
    }
    private void loadDashboard() {
        lblTotalMaterials.setText(String.valueOf(controller.getTotalMaterials()));
        lblTotalCleaners.setText(String.valueOf(controller.getTotalCleaners()));
        lblLowStock.setText(String.valueOf(controller.getLowStockCount()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalMaterials = new javax.swing.JLabel();
        lblTotalCleaners = new javax.swing.JLabel();
        lblLowStock = new javax.swing.JLabel();
        lblTotalUsers = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setName("DashboardForm"); // NOI18N

        lblTotalMaterials.setText("Total Materials");
        lblTotalMaterials.setName("lblTotalMaterials"); // NOI18N

        lblTotalCleaners.setText("Total Cleaners");
        lblTotalCleaners.setName("lblTotalCleaners"); // NOI18N

        lblLowStock.setText("Low Stock");
        lblLowStock.setName("lblLowStock"); // NOI18N

        lblTotalUsers.setText("Total Users");
        lblTotalUsers.setName("lblTotalUsers"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("tblRecentIssues"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jButton1.setLabel("Refresh");
        jButton1.setName("btnRefresh"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(181, 181, 181)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTotalMaterials)
                                .addComponent(lblLowStock))
                            .addGap(237, 237, 237)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTotalCleaners)
                                .addComponent(lblTotalUsers)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalMaterials)
                    .addComponent(lblTotalCleaners))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLowStock)
                    .addComponent(lblTotalUsers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblLowStock;
    private javax.swing.JLabel lblTotalCleaners;
    private javax.swing.JLabel lblTotalMaterials;
    private javax.swing.JLabel lblTotalUsers;
    // End of variables declaration//GEN-END:variables

}
