package za.belgiumcampus.cleaninginventory.view.issuesForm;

import java.sql.SQLException;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import za.belgiumcampus.cleaninginventory.controller.IssueController;
import za.belgiumcampus.cleaninginventory.model.Issue;
import za.belgiumcampus.cleaninginventory.util.Validation;


public class IssuesForm extends javax.swing.JFrame {
    
    private final IssueController issueController;
    private DefaultTableModel tableModel;
    private int selectedIssuanceId = -1;

    public IssuesForm() {
        initComponents();
        issueController = new IssueController();
        tableModel = (DefaultTableModel) tblIssue.getModel();
        loadIssuances();
    }

    private void loadIssuances() {
        try {
            tableModel.setRowCount(0);
            List<Issue> list = issueController.getAllIssuances();

            for (Issue i : list) {
                tableModel.addRow(new Object[]{
                    i.getIssuanceId(),
                    i.getMaterialId(),
                    i.getCleanerId(),
                    i.getQuantityIssued(),
                    i.getCreatedAt()
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
     private void clearFields() {
        txtMaterialIdI.setText("");
        txtCleanerIdI.setText("");
        txtQuantityI.setText("");
        txtSearchI.setText("");
        selectedIssuanceId = -1;
        txtMaterialIdI.requestFocus();
    }

    private void searchIssuances() {
        try {
            tableModel.setRowCount(0);
            String searchText = txtSearchI.getText().trim();
            List<Issue> list = issueController.searchIssuances(searchText);

            for (Issue i : list) {
                tableModel.addRow(new Object[]{
                    i.getIssuanceId(),
                    i.getMaterialId(),
                    i.getCleanerId(),
                    i.getQuantityIssued(),
                    i.getCreatedAt()
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IssuesForm.class.getName());

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIssue = new javax.swing.JTable();
        btnAddI = new javax.swing.JButton();
        btnUpdateI = new javax.swing.JButton();
        btnDeleteI = new javax.swing.JButton();
        btnClearI = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearchI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaterialIdI = new javax.swing.JTextField();
        txtCleanerIdI = new javax.swing.JTextField();
        txtQuantityI = new javax.swing.JTextField();
        btnSearchI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Issuance Management");

        tblIssue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IssuanceID", "MaterialID", "CleanerID", "QuantityIssued"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblIssue);

        btnAddI.setText("Add issuance");
        btnAddI.addActionListener(this::btnAddIActionPerformed);

        btnUpdateI.setText("Update Issuance");
        btnUpdateI.addActionListener(this::btnUpdateIActionPerformed);

        btnDeleteI.setText("Delete Issuance");
        btnDeleteI.addActionListener(this::btnDeleteIActionPerformed);

        btnClearI.setText("Clear Issuance");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Search Issuance");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Material ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cleaner ID");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Quantity");

        btnSearchI.setText("Search");
        btnSearchI.setToolTipText("");
        btnSearchI.setActionCommand("");
        btnSearchI.addActionListener(this::btnSearchIActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaterialIdI, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(txtCleanerIdI)
                                    .addComponent(txtQuantityI, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSearchI)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearchI, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddI)
                                .addGap(31, 31, 31)
                                .addComponent(btnUpdateI)
                                .addGap(30, 30, 30)
                                .addComponent(btnDeleteI)
                                .addGap(30, 30, 30)
                                .addComponent(btnClearI))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddI)
                            .addComponent(btnUpdateI)
                            .addComponent(btnDeleteI)
                            .addComponent(btnClearI)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaterialIdI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtCleanerIdI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantityI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtSearchI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchI)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIActionPerformed
         try {
            Issue issuance = new Issue();

            issuance.setMaterialId(Integer.parseInt(txtMaterialIdI.getText().trim()));
            issuance.setCleanerId(Integer.parseInt(txtCleanerIdI.getText().trim()));
            issuance.setQuantityIssued(Integer.parseInt(txtQuantityI.getText().trim()));

            int newId = issueController.addIssuance(issuance);

            if (newId > 0) {
                JOptionPane.showMessageDialog(this, "Issuance created with ID: " + newId);
                loadIssuances();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to create issuance.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Material ID, Cleaner ID and Quantity must be numbers.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddIActionPerformed

    private void btnUpdateIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateIActionPerformed
    
        try {
            if (selectedIssuanceId == -1) {
                JOptionPane.showMessageDialog(this, "Please select an issuance first.");
                return;
            }

            Issue issuance = new Issue();
            issuance.setIssuanceId(selectedIssuanceId);
            issuance.setMaterialId(Integer.parseInt(txtMaterialIdI.getText().trim()));
            issuance.setCleanerId(Integer.parseInt(txtCleanerIdI.getText().trim()));
            issuance.setQuantityIssued(Integer.parseInt(txtQuantityI.getText().trim()));

            if (issueController.updateIssuance(issuance)) {
                JOptionPane.showMessageDialog(this, "Issuance updated successfully.");
                loadIssuances();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update issuance.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateIActionPerformed

    private void btnDeleteIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteIActionPerformed
    
        if (selectedIssuanceId == -1) {
            JOptionPane.showMessageDialog(this, "Please select an issuance first.");
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this, "Delete this issuance?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            try {
                if (issueController.deleteIssuance(selectedIssuanceId)) {
                    JOptionPane.showMessageDialog(this, "Issuance deleted.");
                    loadIssuances();
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete issuance.");
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnDeleteIActionPerformed

    private void btnSearchIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIActionPerformed
        searchIssuances();
    }//GEN-LAST:event_btnSearchIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssuesForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddI;
    private javax.swing.JButton btnClearI;
    private javax.swing.JButton btnDeleteI;
    private javax.swing.JButton btnSearchI;
    private javax.swing.JButton btnUpdateI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIssue;
    private javax.swing.JTextField txtCleanerIdI;
    private javax.swing.JTextField txtMaterialIdI;
    private javax.swing.JTextField txtQuantityI;
    private javax.swing.JTextField txtSearchI;
    // End of variables declaration//GEN-END:variables
}
