package za.belgiumcampus.cleaninginventory.view.reports;

import java.sql.SQLException;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import za.belgiumcampus.cleaninginventory.controller.ReportController;
import za.belgiumcampus.cleaninginventory.model.InventoryReport;
import za.belgiumcampus.cleaninginventory.model.LowStockReport;
import za.belgiumcampus.cleaninginventory.model.IssuanceHistoryReport;
import za.belgiumcampus.cleaninginventory.model.MaterialUsageReport;
import za.belgiumcampus.cleaninginventory.util.Validation;

public class ReportsForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportsForm.class.getName());

    private final ReportController reportsController;
    private DefaultTableModel tableModel;

    public ReportsForm() {
        initComponents();
        reportsController = new ReportController();
        tableModel = (DefaultTableModel) tblReports.getModel();
    }

    private void clearFilters() {
        txtCleanerIDR.setText("");
        txtMaterialIDR.setText("");
        txtCleanerIDR.requestFocus();
    }
    
    private void loadInventoryReportTable(List<InventoryReport> list) {
        String[] columns = {"Material ID", "Material Name", "Quantity Available"};
        tableModel = new DefaultTableModel(columns, 0);

        for (InventoryReport r : list) {
            tableModel.addRow(new Object[]{
                r.getMaterialId(),
                r.getMaterialName(),
                r.getQuantityAvailable()
            });
        }

        tblReports.setModel(tableModel);
    }

    private void loadLowStockReportTable(List<LowStockReport> list) {
        String[] columns = {"Material ID", "Material Name", "Quantity Available"};
        tableModel = new DefaultTableModel(columns, 0);

        for (LowStockReport r : list) {
            tableModel.addRow(new Object[]{
                r.getMaterialId(),
                r.getMaterialName(),
                r.getQuantityAvailable()
            });
        }

        tblReports.setModel(tableModel);
    }

    private void loadIssuanceHistoryTable(List<IssuanceHistoryReport> list) {
        String[] columns = {"Issuance ID", "Material ID", "Material Name", "Quantity Issued", "Issued At"};
        tableModel = new DefaultTableModel(columns, 0);

        for (IssuanceHistoryReport r : list) {
            tableModel.addRow(new Object[]{
                r.getIssuanceId(),
                r.getMaterialId(),
                r.getMaterialName(),
                r.getQuantityIssued(),
                r.getIssuedAt()
            });
        }

        tblReports.setModel(tableModel);
    }

    private void loadMaterialUsageTable(List<MaterialUsageReport> list) {
        String[] columns = {"Issuance ID", "Cleaner Name", "Quantity Issued", "Issued At"};
        tableModel = new DefaultTableModel(columns, 0);

        for (MaterialUsageReport r : list) {
            tableModel.addRow(new Object[]{
                r.getIssuanceId(),
                r.getCleanerName(),
                r.getQuantityIssued(),
                r.getIssuedAt()
            });
        }

        tblReports.setModel(tableModel);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        btnInvreport = new javax.swing.JButton();
        btnStocklow = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnMusage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCleanerIDR = new javax.swing.JTextField();
        txtMaterialIDR = new javax.swing.JTextField();
        btnRunR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtThreshold = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reports Dashboard");

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReports);

        btnInvreport.setText("Inventory Report");
        btnInvreport.addActionListener(this::btnInvreportActionPerformed);

        btnStocklow.setText("low Stock Report");
        btnStocklow.addActionListener(this::btnStocklowActionPerformed);

        btnHistory.setText("Issuance Hisotry");
        btnHistory.addActionListener(this::btnHistoryActionPerformed);

        btnMusage.setText("Material Usage");
        btnMusage.addActionListener(this::btnMusageActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Filter");

        jLabel3.setText("CleanerID");

        jLabel4.setText("Material ID");

        btnRunR.setText("Run Report");

        jLabel5.setText("Threshold");

        txtThreshold.addActionListener(this::txtThresholdActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnInvreport)
                                .addGap(29, 29, 29)
                                .addComponent(btnStocklow)
                                .addGap(52, 52, 52)
                                .addComponent(btnHistory)
                                .addGap(41, 41, 41)
                                .addComponent(btnMusage))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtCleanerIDR, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaterialIDR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRunR)
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCleanerIDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaterialIDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRunR)
                    .addComponent(jLabel5)
                    .addComponent(txtThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInvreport)
                    .addComponent(btnStocklow)
                    .addComponent(btnHistory)
                    .addComponent(btnMusage))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStocklowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStocklowActionPerformed
    try {
            if (!Validation.isPositiveInteger(txtThreshold.getText())) {
                JOptionPane.showMessageDialog(this, "Threshold must be a number.");
                return;
            }

            int threshold = Integer.parseInt(txtThreshold.getText());
            List<LowStockReport> list = reportsController.getLowStockReport(threshold);
            loadLowStockReportTable(list);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnStocklowActionPerformed

    private void txtThresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThresholdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThresholdActionPerformed

    private void btnInvreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvreportActionPerformed
       try {
            List<InventoryReport> list = reportsController.getInventoryReport();
            loadInventoryReportTable(list);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInvreportActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
     try {
            if (!Validation.isPositiveInteger(txtCleanerIDR.getText())) {
                JOptionPane.showMessageDialog(this, "Cleaner ID must be a number.");
                return;
            }

            int cleanerId = Integer.parseInt(txtCleanerIDR.getText());
            List<IssuanceHistoryReport> list = reportsController.getIssuanceHistory(cleanerId);
            loadIssuanceHistoryTable(list);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnMusageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusageActionPerformed
     try {
            if (!Validation.isPositiveInteger(txtMaterialIDR.getText())) {
                JOptionPane.showMessageDialog(this, "Material ID must be a number.");
                return;
            }

            int materialId = Integer.parseInt(txtMaterialIDR.getText());
            List<MaterialUsageReport> list = reportsController.getMaterialUsageReport(materialId);
            loadMaterialUsageTable(list);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMusageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnInvreport;
    private javax.swing.JButton btnMusage;
    private javax.swing.JButton btnRunR;
    private javax.swing.JButton btnStocklow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReports;
    private javax.swing.JTextField txtCleanerIDR;
    private javax.swing.JTextField txtMaterialIDR;
    private javax.swing.JTextField txtThreshold;
    // End of variables declaration//GEN-END:variables
}
